### PR TITLE
Fix trivial spelling errors

### PR DESCRIPTION
**Pull request by ottok**
- handshak -> handshake
- occured -> occurred
- releated -> related
- reponse -> response
- seperated -> separated
- sucess -> success
- use use -> use

### CODE REVIEW

**Comment by ottok** [comment]
Travis CI failed on mtr test `main.timezone3` and unit test `test_conc632` but I don't see exactly why, and git head 3.3 was already broken (https://github.com/mariadb-corporation/mariadb-connector-c/runs/11816127568) so I don't think these spelling fixes broken the CI and this PR should be merged despite failing CI (or I can rebase it on latest git head 3.3 when you have it fixed).

**Comment by ottok** [comment]
Hi! This has been open for two weeks. The topic itself is fairly trivial. Can you please merge or give feedback what changes you wish to see in it?

**Comment by ottok** [comment]
Rebased on latest 3.3.

CI tests are failing on issues that are not due to this PR but already regressed on mainline (missing grants, SQL procedure syntax errors, missing test data file etc).

Merging this PR is safe.

**Comment by ottok** [comment]
@LinuxJedi Could you please review and merge this? The MariaDB Connector C is embedded in the MariaDB Server which the Foundation publishes.

**Comment by LinuxJedi** [comment]
> @LinuxJedi Could you please review and merge this? The MariaDB Connector C is embedded in the MariaDB Server which the Foundation publishes.

As this is a MariaDB Corporation project, I do not have sufficient privileges to do so.

**Comment by 9EOR9** [comment]
man pages are created from [Wiki](https://github.com/mariadb-corporation/mariadb-connector-c/wiki) with pandoc markdown to man converter.
For next C/C version we will create man pages automatically (this feature will require pandoc and option -DWITH_DOCS=ON).
Beside the handshake typo all other typos were already fixed in Wiki.

**Comment by dlenski** [comment]
How about `intitial` in https://github.com/mariadb-corporation/mariadb-connector-c/blob/3.3/libmariadb/mariadb_lib.c#L1967?

**Comment by ottok** [comment]
I rebased this now on latest 3.3. Can you @9EOR9 please merge this?

The fixes are trivial spelling fixes and the PR has been open for a year now. It should not matter if the man pages are copied from elsewhere, this PR still fixes them in the target for now and there is no downside to it.

**Comment by illuusio** [comment]
> man pages are created from [Wiki](https://github.com/mariadb-corporation/mariadb-connector-c/wiki) with pandoc markdown to man converter. For next C/C version we will create man pages automatically (this feature will require pandoc and option -DWITH_DOCS=ON). Beside the handshake typo all other typos were already fixed in Wiki.

Sorry being bit late in party but could man pages regenerated with newer pandoc as it would fix warnings like:
```
W: libmariadb-dev: groff-message troff:<standard input>:102: warning: cannot select font 'C' [usr/share/man/man3/mariadb_get_infov.3.gz:45]
W: libmariadb-dev: groff-message troff:<standard input>:105: warning: cannot select font 'C' [usr/share/man/man3/mysql_real_connect.3.gz:16]
W: libmariadb-dev: groff-message troff:<standard input>:106: warning: cannot select font 'C' [usr/share/man/man3/mysql_optionsv.3.gz:51]
...
```
According to this https://github.com/jgm/pandoc/issues/9020

**Comment by 9EOR9** [comment]
@ottok All these bugs have been fixed in Connector/C Github Wiki. I recently fixed the creation of manpages and pushed it into 3.3 (now cmake options -DWITH_DOCS=ON should build man pages if python3 and doxygen are installed). The typo in result test was fixed too, however there was a missing underscore, not a double "use".
@illuusio: manpages were removed from the repository, you need to build it with a newer pandoc (cmake option: -DWITH_DOCS=ON).

**Comment by ottok** [comment]
For the record, the man pages continue to have the spelling errors on the 3.3 branch as this PR was not merged.

For the 3.4 branch the man pages were updated in https://github.com/mariadb-corporation/mariadb-connector-c/commit/e06ff35fd76f92457b4cff71e220c18203dc5f27 which brought in most of the spelling fixes.

**Pull request closed without merging**
