### PR TITLE
CONC-283: Install libmariadb.pc

### PR DESCRIPTION
**Pull request by candrews**
Thanks to astavale astavale@yahoo.co.uk and tabata shintaro

https://jira.mariadb.org/browse/CONC-283

### CODE REVIEW

**Comment by 9EOR9** [comment]
This was already fixed in 3.0.7

**Comment by Whissi** [comment]
@9E0R9 But your solution is wrong: 3.0.7 will set
> Libs: -L${libdir} -lmariadb -lz -ldl -lm -lpthread -lgnutls

but "Libs" should only list what is required to link against *libmariadb*. Things like `-lz -ldl -lm -lpthread -lgnutls` can be listed in "Libs.private" but exposing in *Libs* is wrong.

**Comment by Whissi** [comment]
Proposed fix:
```diff
--- a/mariadb_config/libmariadb.pc.in
+++ b/mariadb_config/libmariadb.pc.in
@@ -7,13 +7,12 @@
 #

 prefix=@CMAKE_INSTALL_PREFIX@
-includedir=${prefix}/@INSTALL_INCLUDEDIR@/@SUFFIX_INSTALL_DIR@
-libdir=${prefix}/@INSTALL_LIBDIR@/@SUFFIX_INSTALL_DIR@
+includedir=${prefix}/include
+libdir=${prefix}/@CMAKE_INSTALL_LIBDIR@

 Name: libmariadb
 Version: @CPACK_PACKAGE_VERSION@
+URL: https://mariadb.com/kb/en/library/mariadb-connector-c/
 Description: MariaDB Connector/C dynamic library
-Cflags: -I${includedir}
-Libs: -L${libdir} -lmariadb @extra_dynamic_LDFLAGS@
-
-
+Cflags: -I${includedir}/mariadb
+Libs: -L${libdir} -lmariadb

```

**Comment by 9E0R9** [comment]
Hi Thomas,

Changing this will most likely break any project which uses mariadb_config.

/Georg

Am So., 2. Dez. 2018, 23:48 hat Thomas Deutschmann <notifications@github.com>
geschrieben:

**Pull request closed without merging**
