### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by ghost**
client/ma_plugin_info.c

### CODE REVIEW

**Comment by ghost** [comment]
Any files not to touch in [mariadb-connector-c ](https://github.com/mariadb-corporation/mariadb-connector-c)aside from the bundled zlib regarding typo corrections?

<hr>

The man pages for example are automatically generated.

```
$ head -n 1 mariadb-connector-c/man/mysql_autocommit.3
.\" Automatically generated by Pandoc 2.5
$ 
```

Some of the headers have exclusively a 'MySQL AB & MySQL Finland AB & TCX DataKonsult AB' copyright.

```
$ grep -nr easyier mariadb-connector-c
mariadb-connector-c/include/ma_global.h:581:/* Typdefs for easyier portability */
$ grep -nr funktions mariadb-connector-c
mariadb-connector-c/include/ma_global.h:744:** Define-funktions for reading and storing in machine independent format
mariadb-connector-c/include/ma_global.h:977:  Define-funktions for reading and storing in machine format from/to
$ grep -nr theese mariadb-connector-c
mariadb-connector-c/include/ma_sys.h:212:  uint         not_pos;        /* Start of not-theese-files */
$ grep -nr theit mariadb-connector-c
mariadb-connector-c/include/ma_global.h:229:/* my_ctype my_to_upper, my_to_lower, my_sort_order gain theit right value */
$
```

Some of the unittest directory files have a Sun or Oracle copyright.

```
$ grep -nr compilicated mariadb-connector-c
mariadb-connector-c/unittest/libmariadb/cursor.c:758:/* Cursors: opening a cursor to a compilicated query with ORDER BY */
$ grep -nr DISTICNT mariadb-connector-c
mariadb-connector-c/unittest/libmariadb/cursor.c:1703:/* Crash when opening a cursor to a query with DISTICNT and no key */
$ grep -nr maually mariadb-connector-c
mariadb-connector-c/unittest/libmariadb/CMakeLists.txt:36:#exclude following tests from ctests, since we need to run them maually with different credentials
$ 
```

Presently the following comment typos could be fixed.

```
#!/bin/sh

sed -i 's/Corpoeation/Corporation/g' mariadb-connector-c/include/ma_compress.h
sed -i 's/acknoledgement/acknowledgement/g' mariadb-connector-c/libmariadb/mariadb_rpl.c
sed -i 's/aloocate/allocate/g' mariadb-connector-c/libmariadb/mariadb_stmt.c
sed -i 's/asynchroneous/asynchronous/g' mariadb-connector-c/include/ma_context.h
sed -i 's/asynchroneous/asynchronous/g' mariadb-connector-c/libmariadb/ma_context.c
sed -i 's/buuld/build/g' mariadb-connector-c/include/ma_pvio.h
sed -i 's/compilastion/compilation/g' mariadb-connector-c/libmariadb/ma_charset.c
sed -i 's/copression/compression/g' mariadb-connector-c/plugins/auth/my_auth.c
sed -i 's/hewbrew/hebrew/g' mariadb-connector-c/libmariadb/ma_charset.c
sed -i 's/inforn/inform/g' mariadb-connector-c/libmariadb/mariadb_lib.c
sed -i 's/knowm/known/g' mariadb-connector-c/libmariadb/mariadb_stmt.c
sed -i 's/lengtht/lengths/g' mariadb-connector-c/plugins/auth/caching_sha2_pw.c
sed -i 's/ninute/minute/g' mariadb-connector-c/libmariadb/mariadb_stmt.c
sed -i 's/nummber/number/g' mariadb-connector-c/libmariadb/mariadb_dyncol.c
sed -i 's/protcols/protocols/g' mariadb-connector-c/libmariadb/ma_pvio.c
sed -i 's/resourses/resources/g' mariadb-connector-c/include/mariadb_dyncol.h
sed -i 's/separetely/separately/g' mariadb-connector-c/libmariadb/ma_dtoa.c
sed -i 's/structutr/structure/g' mariadb-connector-c/libmariadb/mariadb_stmt.c
sed -i 's/truncantion/truncation/g' mariadb-connector-c/plugins/auth/CMakeLists.txt
```

**Comment by ghost** [comment]
These files contain typos in the code.

```
$ grep -nr occured mariadb-connector-c/{include,libmariadb}
mariadb-connector-c/include/ma_context.h:181:  unsigned int events_occured;
mariadb-connector-c/libmariadb/mariadb_async.c:112:    if (b->events_occured & MYSQL_WAIT_TIMEOUT)
mariadb-connector-c/libmariadb/mariadb_async.c:251:  b->events_occured= ready_status;                                            \
mariadb-connector-c/libmariadb/mariadb_async.c:307:  b->events_occured= ready_status;                                            \
mariadb-connector-c/libmariadb/ma_pvio.c:212:    if (b->events_occured & MYSQL_WAIT_TIMEOUT)
mariadb-connector-c/libmariadb/ma_pvio.c:338:    if (b->events_occured & MYSQL_WAIT_TIMEOUT)
mariadb-connector-c/libmariadb/ma_pvio.c:463:  return (b->events_occured & MYSQL_WAIT_TIMEOUT) ? 0 : 1;
$ 
```

If approved, I can add another commit as 'code typos'  implementing the below. 

```
$ sed -i 's/occured/occurred/g' mariadb-connector-c/include/ma_context.h
$ sed -i 's/occured/occurred/g' mariadb-connector-c/libmariadb/mariadb_async.c
$ sed -i 's/occured/occurred/g' mariadb-connector-c/libmariadb/ma_pvio.c
$ 
```

**Comment by 9EOR9** [comment]
Thanks, fixed in rev. 3f7719c74df0eea8b8fe2ce92b229fea49407223

About copyright:
Files with MySQL AB & MySQL Finland AB & TCX DataKonsult AB' copyright are from MySQL 3.23 (LGPL)
PHP Group copyright comes from ported mysqlnd functions
Unittests have Oracle/MySQL copyright and are licensed under GPL (and therefore not shipped in packages)

**Comment by ghost** [comment]
> The man pages for example are automatically generated.

see `#201`

<hr>

> Some of the unittest directory files have a Sun or Oracle copyright.

from https://github.com/mariadb-corporation/mariadb-connector-c/pull/44 it appears that some unittest subdirectory files have been typo corrected

in the next month probably I can submit a PR for unittest directory typo fixes

also for 'MySQL AB & MySQL Finland AB & TCX DataKonsult AB' copyrighted files

**Pull request closed without merging**
