### PR TITLE
fix compiling for android

### PR DESCRIPTION
**Pull request by Rechi**

### CODE REVIEW

**Comment by Rechi** [comment]
@9EOR9 ping

**Comment by 9EOR9** [comment]
Hi,

we removed already the progname detection from mariadb_lib.c, platform support for Android and arm will be part of C/C 3.0.4 - see also branch c-3.0-portable

**Comment by Rechi** [comment]
I removed the `libmariadb/mariadb_lib.c` as it isn't need anymore (and caused merge conflicts).
The `ushort` detection is still needed on top of master to build for android. I haven't tried to build 3.0-portable branch yet.

**Comment by 9EOR9** [comment]
rev. 7b07d27bbeedea9e43d4826b4fb297a43fa04e8d (3.1 branch)

**Pull request closed without merging**
